[package]
authors = ["Nathan Ringo <remexre@gmail.com>"]
description = "The OftLisp bootstrapper."
license = "Apache-2.0/MIT"
name = "oftb"
version = "0.1.0"

[dependencies]
either = "1.4.0"
failure = "0.1.1"
log = "0.4.1"
pest = "1.0.6"
pest_derive = "1.0.6"
semver = "0.9.0"
stderrlog = { version = "0.3.1-pre", git = "https://github.com/remexre/stderrlog-rs.git" }
structopt = "0.2.5"
symbol = "0.1.1"

[dev-dependencies]
proptest = "0.5.1"

[[bin]]
doc = false
name = "oftb"
path = "src/bin/main.rs"
